workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: v20
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.offlinegamesroom.app
      groups:
        - app_store_credentials
    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Expo prebuild
        script: npx expo prebuild --platform ios --clean

      - name: Install CocoaPods
        script: cd ios && pod install

      - name: Set up keychain
        script: keychain initialize

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files com.offlinegamesroom.app \
            --type IOS_APP_STORE \
            --create

      - name: Add certificates to keychain
        script: keychain add-certificates

      - name: Apply provisioning profiles
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          WORKSPACE=$(find ios -name "*.xcworkspace" | head -1)
          SCHEME=$(basename "$WORKSPACE" .xcworkspace)
          echo "Building workspace: $WORKSPACE  scheme: $SCHEME"
          xcode-project build-ipa \
            --workspace "$WORKSPACE" \
            --scheme "$SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        cancel_previous_submissions: true
