workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: v20
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Expo prebuild
        script: npx expo prebuild --platform ios --clean

      - name: Install CocoaPods
        script: cd ios && pod install

      - name: Set up keychain
        script: keychain initialize

      - name: Fetch signing files
        script: |
          echo "$CERT_PRIVATE_KEY" | base64 --decode > /tmp/cert_key.pem
          app-store-connect fetch-signing-files com.offlinegamesroom.app \
            --type IOS_APP_STORE \
            --certificate-key @file:/tmp/cert_key.pem \
            --create

      - name: Add certificates to keychain
        script: keychain add-certificates

      - name: Apply provisioning profiles
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          WORKSPACE=$(find ios -name "*.xcworkspace" -not -path "*.xcodeproj/*" | head -1)
          SCHEME=$(basename "$WORKSPACE" .xcworkspace)
          echo "Building workspace: $WORKSPACE  scheme: $SCHEME"
          xcode-project build-ipa \
            --workspace "$WORKSPACE" \
            --scheme "$SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

  android-release:
    name: Android Release
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      node: v20
      java: 17
      groups:
        - google_play_credentials
    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Set up local.properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties

      - name: Expo prebuild
        script: npx expo prebuild --platform android --clean

      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
          cat >> android/gradle.properties << EOF
          MYAPP_UPLOAD_STORE_FILE=$CM_KEYSTORE_PATH
          MYAPP_UPLOAD_KEY_ALIAS=$CM_KEY_ALIAS
          MYAPP_UPLOAD_STORE_PASSWORD=$CM_KEYSTORE_PASSWORD
          MYAPP_UPLOAD_KEY_PASSWORD=$CM_KEY_PASSWORD
          EOF

      - name: Build Android App Bundle
        script: |
          cd android
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
