import { GameMetadata } from '../types';

export const GAMES: GameMetadata[] = [
  {
    id: 'tic-tac-toe',
    name: 'Tic Tac Toe',
    icon: '❌',
    description: 'Classic X vs O',
    color: '#ff5e57',
    category: 'Arcade',
  },
  {
    id: 'snake',
    name: 'Snake',
    icon: '🐍',
    description: 'Eat and grow',
    color: '#1dd1a1',
    category: 'Arcade',
  },
  {
    id: '2048',
    name: '2048',
    icon: '2048',
    description: 'Merge numbers',
    color: '#ff9f43',
    category: 'Puzzle',
  },
  {
    id: 'minesweeper',
    name: 'Minesweeper',
    icon: '💣',
    description: 'Avoid mines',
    color: '#5f27cd',
    category: 'Puzzle',
  },
  {
    id: 'connect-four',
    name: '4 in a Row',
    icon: '🔴',
    description: 'Get 4 in a row',
    color: '#feca57',
    category: 'Board',
  },
  {
    id: 'tetris',
    name: 'Block Drop',
    icon: '🧱',
    description: 'Stack the falling blocks',
    color: '#48dbfb',
    category: 'Arcade',
  },
  {
    id: 'maze',
    name: 'Maze',
    icon: '🌀',
    description: 'Find the exit',
    color: '#ff9ff3',
    category: 'Puzzle',
  },
  {
    id: 'solitaire',
    name: 'Solitaire',
    icon: '🃏',
    description: 'Klondike',
    color: '#ee5253',
    category: 'Card',
  },
  {
    id: 'sudoku',
    name: 'Sudoku',
    icon: '🔢',
    description: 'Number logic',
    color: '#00d2d3',
    category: 'Logic',
  },
  {
    id: 'reversi',
    name: 'Reversi',
    icon: '⚪',
    description: 'Flip discs',
    color: '#8395a7',
    category: 'Board',
  },
  {
    id: 'checkers',
    name: 'Checkers',
    icon: '🏁',
    description: 'Jump & King',
    color: '#222f3e',
    category: 'Board',
  },
  {
    id: 'chess',
    name: 'Chess',
    icon: '♟️',
    description: 'Checkmate',
    color: '#576574',
    category: 'Board',
  },
  {
    id: 'blackjack',
    name: 'Blackjack',
    icon: '💰',
    description: 'Beat dealer',
    color: '#341f97',
    category: 'Card',
  },
  {
    id: 'poker',
    name: 'Poker',
    icon: '🎰',
    description: 'Texas Holdem',
    color: '#54a0ff',
    category: 'Card',
  },
  {
    id: 'hearts',
    name: 'Hearts',
    icon: '💔',
    description: 'Avoid hearts',
    color: '#ff9ff3',
    category: 'Card',
  },
  {
    id: 'water-sort',
    name: 'Water Sort',
    icon: '🧪',
    description: 'Color puzzle',
    color: '#0abde3',
    category: 'Puzzle',
  },
  {
    id: 'word-search',
    name: 'Word Search',
    icon: '🔍',
    description: 'Find words',
    color: '#10ac84',
    category: 'Logic',
  },
  {
    id: 'brick-breaker',
    name: 'Brick Breaker',
    icon: '☄️',
    description: 'Smash bricks',
    color: '#ff9f43',
    category: 'Arcade',
  },
  {
    id: 'mahjong',
    name: 'Mahjong',
    icon: '🀄',
    description: 'Tile matching',
    color: '#ffbe76',
    category: 'Puzzle',
  },
  {
    id: 'hangman',
    name: 'Hangman',
    icon: '😵',
    description: 'Guess word',
    color: '#ee5253',
    category: 'Logic',
  },
  {
    id: 'simon-says',
    name: 'Memory Lights',
    icon: '🚨',
    description: 'Memory',
    color: '#54a0ff',
    category: 'Memory',
  },
  {
    id: 'memory-match',
    name: 'Memory',
    icon: '🧠',
    description: 'Match pairs',
    color: '#ff9ff3',
    category: 'Memory',
  },
  {
    id: 'word-guess',
    name: 'Word Guess',
    icon: '🔡',
    description: '5 letters',
    color: '#1dd1a1',
    category: 'Logic',
  },
  {
    id: 'spider-solitaire',
    name: 'Spider',
    icon: '🕷️',
    description: '8 decks',
    color: '#222f3e',
    category: 'Card',
  },
  {
    id: 'battleship',
    name: 'Sea Battle',
    icon: '🚢',
    description: 'Naval war',
    color: '#48dbfb',
    category: 'Logic',
  },
  {
    id: 'spades',
    name: 'Spades',
    icon: '⚔️',
    description: 'Bidding war',
    color: '#576574',
    category: 'Card',
  },
  {
    id: 'code-breaker',
    name: 'Code Breaker',
    icon: '🕵️',
    description: 'Crack code',
    color: '#feca57',
    category: 'Logic',
  },
  {
    id: 'freecell',
    name: 'FreeCell',
    icon: '🏰',
    description: 'Solitaire',
    color: '#1dd1a1',
    category: 'Card',
  },
  {
    id: 'dominoes',
    name: 'Dominoes',
    icon: '🁫',
    description: 'Tile match',
    color: '#8395a7',
    category: 'Board',
  },
  {
    id: 'backgammon',
    name: 'Backgammon',
    icon: '🎲',
    description: 'Dice race',
    color: '#ff9f43',
    category: 'Board',
  },
];

export const SNAKE_GRID_SIZE = 15;
export const SNAKE_TICK_MS = 150;
